### ISSUE TITLE
Front to Back Integration

### ISSUE THREAD

**Issue by jonathan-bravo** [Andrewtomp/Software-Engineering#28]
Need to either build an internal package OR us a GitHub workflow to automate the building of the React front end into a static page that can be served by the back end.

Something like this:

```yaml
name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # change as needed

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the React app
      - name: Build the React app
        run: npm run build

      # Deploy the build folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
```

Once that is done we need to make sure that the front is able to send information to the back and vice versa.
